// File generated by FlutterFire CLI, then changed so the API keys are not
// committed to git: they come from the env file (FIREBASE_API_KEY_ANDROID /
// FIREBASE_API_KEY_IOS, see env/dev.json.example). If you run
// `flutterfire configure` again, re-apply this change before committing.
// ignore_for_file: type=lint
import 'package:app_boilerplate/core/config/env_config.dart';
import 'package:firebase_core/firebase_core.dart'
    show
        FirebaseOptions;
import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: EnvConfig.firebaseApiKeyAndroid,
    appId: '1:868667169698:android:a7861b97ee4ee40687f0fb',
    messagingSenderId: '868667169698',
    projectId: 'form-fitness-7f74d',
    storageBucket: 'form-fitness-7f74d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvConfig.firebaseApiKeyIos,
    appId: '1:868667169698:ios:7eea0e5a35ccc50687f0fb',
    messagingSenderId: '868667169698',
    projectId: 'form-fitness-7f74d',
    storageBucket: 'form-fitness-7f74d.firebasestorage.app',
    iosBundleId: 'com.formfitness.app',
  );
}
